from __future__ import annotations

from collections.abc import Mapping

SUPPORTED_LOCALES = {"es", "en"}
DEFAULT_LOCALE = "es"

MESSAGES: dict[str, dict[str, str]] = {
    "es": {
        "product": "Radar Rudo", "assistant": "Rudy encuentra las historias.", "connect": "Conectar con Strava", "visible_default_note": "Por defecto contabilizamos actividades visibles para Todos y Seguidores. Puedes incluir privadas después desde Configuración.", "visible_dashboard_note": "Radar muestra totales y comparaciones; no publica horarios, nombres de entrenamientos ni actividades individuales.", "review_access": "Revisar acceso", "totals_only_note": "En el equipo solo mostramos totales, comparaciones y rankings. No mostramos horarios ni actividades individuales.", "disable_private": "Dejar de incluir mis actividades privadas", "login": "Entrar al radar", "register": "Registrarme con Strava", "login_detail": "Si ya diste permiso, Strava conservará tu acceso actual y te regresará al radar.", "register_or_permissions": "Registrarme o cambiar permisos", "register_visible": "Registrarme con actividades visibles", "connect_default_detail": "Usaremos únicamente tus actividades visibles. Puedes ampliar el acceso después.", "access_title": "¿También quieres incluir actividades privadas?", "access_explanation": "Estas opciones sí abren la pantalla de autorización de Strava.", "visible_access": "Actividades visibles", "visible_access_detail": "Incluye Todos y Seguidores; excluye Solo tú.", "private_access": "Registrarme incluyendo privadas", "private_access_detail": "Incluye también las actividades marcadas como Solo tú.", "recommended": "RECOMENDADO", "enable_private": "Incluir mis actividades privadas", "private_enabled": "Actividades privadas incluidas", "account_settings": "Configuración de cuenta", "strava_access": "Acceso a Strava", "private_scope_active": "Radar puede sincronizar tus actividades visibles y las marcadas como Solo tú.", "visible_scope_active": "Radar sincroniza tus actividades visibles para Todos y Seguidores.", "session": "Sesión", "danger_zone": "Zona de riesgo", "delete_account_explanation": "Esta acción elimina tu cuenta y datos de Radar Rudo y revoca su acceso a Strava. No elimina tu cuenta ni tus actividades de Strava.", "back_to_radar": "Volver al radar",
        "privacy": "Privacidad", "language_es": "ES", "language_en": "EN", "club_moving": "EL CLUB EN MOVIMIENTO",
        "hero": "Tus kilómetros ya cuentan una historia.", "intro": "Conecta Strava. Rudy encuentra el ritmo del equipo, reconoce la constancia y encuentra las historias detrás de cada entrenamiento.",
        "exclusive": "Exclusivo para RUD@S.", "activities": "Actividades", "distance": "Distancia", "active_days": "Días activos", "elevation": "Desnivel",
        "this_week": "Esta semana", "last_week": "Semana pasada", "this_month": "Este mes", "last_month": "Mes pasado", "two_months_ago": "Hace 2 meses", "friendly_ranking": "Ranking amistoso", "live": "EN VIVO", "no_activity": "Aún sin actividad",
        "logout": "Salir ↗", "on_radar": "EN EL RADAR", "team_moving": "RUD@S EN MOVIMIENTO", "last_sync": "Última sincronización", "pending": "pendiente",
        "verified_members": "Solo miembros verificados de RUD@S.", "sync_ready": "Sincronización lista", "reviewed_activities": "{count} actividades revisadas",
        "welcome": "Qué onda,", "kilometers_counting": "Los kilómetros ya están contando para el equipo.", "something_wrong": "Algo se cruzó en el camino", "back": "Volver",
        "not_member_title": "Rudy todavía no te encuentra en RUD@S 👀", "not_member_text": "Radar Rudo es exclusivo para miembros del club RUD@S en Strava.", "club_check_unavailable": "La autorización quedó registrada, pero Strava no permitió confirmar el club en este momento. El administrador de RUD@S podrá revisarla desde Radar Rudo.", "club_review_pending": "La autorización quedó registrada para revisión. Si ya perteneces al club, avisa al administrador de RUD@S para revalidarla.",
        "privacy_title": "Privacidad de Radar Rudo", "privacy_intro": "Radar Rudo usa la conexión autorizada con Strava para crear métricas privadas de RUD@S.",
        "privacy_data_title": "Datos que guardamos", "privacy_data_text": "Guardamos tu identificador de Strava, nombre, foto de perfil, permisos concedidos, tokens cifrados y resúmenes de actividad: deporte, fecha, visibilidad, distancia, duración, desnivel, velocidad, calorías y métricas de esfuerzo cuando Strava las entrega. Conservamos hasta un año de estos resúmenes para comparaciones históricas. No guardamos GPS, polylines, rutas ni secuencias biométricas.",
        "privacy_use_title": "Cómo los usamos", "privacy_use_text": "Los usamos para verificar tu pertenencia a RUD@S, sincronizar actividades y mostrar tu panel y rankings internos. No vendemos datos ni los usamos para publicidad.",
        "privacy_control_title": "Control, acceso y eliminación", "privacy_control_text": "Desde Configuración puedes descargar una copia de los datos que Radar conserva sobre ti, incluir o retirar el acceso a actividades Solo tú y eliminar tu cuenta. Al retirar el acceso privado, Radar elimina las actividades que dejan de ser accesibles y recalcula los totales. También puedes revocar Radar Rudo desde Strava.",
        "privacy_retention_title": "Conservación y contacto", "privacy_retention_text": "Conservamos los datos mientras mantengas autorizada la aplicación. Para solicitudes de privacidad contacta al administrador de RUD@S.",
        "delete_data": "Eliminar mi cuenta de Radar Rudo y mis datos", "delete_confirm": "Se eliminará tu cuenta de Radar Rudo, tus datos locales y la autorización de esta app. Tu cuenta y actividades de Strava no se borrarán. Para regresar deberás conectar Strava otra vez.",
        "data_deleted": "Tu cuenta y datos de Radar Rudo fueron eliminados.", "powered_by": "Compatible con Strava", "positions": "Tabla de posiciones", "ranked_by_time": "Ordenada por tiempo activo", "athlete": "Atleta", "athlete_breakdown": "DESGLOSE DEL EQUIPO", "breakdown_privacy_note": "Totales por tipo de actividad. Sin horarios, rutas ni entrenamientos individuales.", "activity_mix": "MEZCLA DE ACTIVIDAD", "what_they_trained": "Qué entrenó en este periodo", "active_time": "Tiempo activo", "registered_members": "miembros registrados", "active_members": "participantes activos", "team_sessions": "sesiones del equipo",
        "weekly_pulse": "PULSO DEL PERIODO", "vs_last_week": "vs. periodo anterior", "more_distance": "más kilómetros totales", "less_distance": "menos kilómetros totales", "same_distance": "mismo kilometraje total", "discipline_activity": "Actividad por disciplina", "biggest_distance_day": "Día con más distancia del equipo", "period_stories": "Historias del periodo", "your_summary": "TU RESUMEN", "total_period": "Total del periodo", "swim": "Natación", "open_water": "Aguas abiertas", "bike": "Bici", "run": "Carrera", "walk": "Caminata / Hiking", "strength": "Fuerza", "cardio": "Cardio indoor", "wellbeing": "Yoga / movilidad", "pace_per_100m": "ritmo /100 m", "pace_per_km": "ritmo /km", "average_speed": "velocidad media", "team_community": "Comunidad RUD@S", "team_participation": "Participación", "team_activity": "Actividad del equipo", "team_time": "Tiempo en movimiento", "team_distance": "Distancia compartida", "team_total": "en este periodo", "complementary_training": "Fuerza y bienestar", "your_longest_day": "Tu día con más distancia", "your_busiest_day": "Tu día con más actividad", "team_busiest_day": "El día que más se movió RUD@S", "team_discipline_days": "Los grandes días del equipo", "participants": "participantes", "sessions": "sesiones", "gym": "Gym", "no_story_yet": "La próxima actividad abre la historia de este periodo.", "weekday_0": "Lunes", "weekday_1": "Martes", "weekday_2": "Miércoles", "weekday_3": "Jueves", "weekday_4": "Viernes", "weekday_5": "Sábado", "weekday_6": "Domingo",
    },
    "en": {
        "product": "Radar Rudo", "assistant": "Rudy finds the stories.", "connect": "Connect with Strava", "visible_default_note": "By default we count activities visible to Everyone and Followers. You can include private activities later in Settings.", "visible_dashboard_note": "Radar shows totals and comparisons; it does not publish schedules, workout names, or individual activities.", "review_access": "Review access", "totals_only_note": "The team only sees totals, comparisons, and rankings. We do not show schedules or individual activities.", "disable_private": "Stop including my private activities", "login": "Enter the radar", "register": "Register with Strava", "login_detail": "If you already granted access, Strava will preserve it and return you to the radar.", "register_or_permissions": "Register or change permissions", "register_visible": "Register with visible activities", "connect_default_detail": "We'll use only your visible activities. You can expand access later.", "access_title": "Also include private activities?", "access_explanation": "These options open Strava's authorization screen.", "visible_access": "Visible activities", "visible_access_detail": "Includes Everyone and Followers; excludes Only You.", "private_access": "Register including private activities", "private_access_detail": "Also includes activities marked Only You.", "recommended": "RECOMMENDED", "enable_private": "Include my private activities", "private_enabled": "Private activities included", "account_settings": "Account settings", "strava_access": "Strava access", "private_scope_active": "Radar can sync your visible activities and those marked Only You.", "visible_scope_active": "Radar syncs activities visible to Everyone and Followers.", "session": "Session", "danger_zone": "Danger zone", "delete_account_explanation": "This deletes your Radar Rudo account and data and revokes its Strava access. It does not delete your Strava account or activities.", "back_to_radar": "Back to the radar",
        "privacy": "Privacy", "language_es": "ES", "language_en": "EN", "club_moving": "THE CLUB IN MOTION",
        "hero": "Your kilometers already tell a story.", "intro": "Connect Strava. Rudy finds the team's rhythm, recognizes consistency, and finds the stories behind every workout.",
        "exclusive": "Only for RUD@S.", "activities": "Activities", "distance": "Distance", "active_days": "Active days", "elevation": "Elevation",
        "this_week": "This week", "last_week": "Last week", "this_month": "This month", "last_month": "Last month", "two_months_ago": "2 months ago", "friendly_ranking": "Friendly ranking", "live": "LIVE", "no_activity": "No activity yet",
        "logout": "Leave ↗", "on_radar": "ON THE RADAR", "team_moving": "RUD@S IN MOTION", "last_sync": "Last sync", "pending": "pending",
        "verified_members": "Only verified RUD@S members.", "sync_ready": "Sync complete", "reviewed_activities": "{count} activities reviewed",
        "welcome": "What's up,", "kilometers_counting": "Your kilometers are already counting for the team.", "something_wrong": "Something got in the way", "back": "Back",
        "not_member_title": "Rudy cannot find you in RUD@S yet 👀", "not_member_text": "Radar Rudo is only for RUD@S club members on Strava.", "club_check_unavailable": "Your authorization was recorded, but Strava could not confirm your club right now. The RUD@S administrator can review it in Radar Rudo.", "club_review_pending": "Your authorization was saved for review. If you are already in the club, ask the RUD@S administrator to revalidate it.",
        "privacy_title": "Radar Rudo privacy", "privacy_intro": "Radar Rudo uses your authorized Strava connection to create private RUD@S metrics.",
        "privacy_data_title": "Data we store", "privacy_data_text": "We store your Strava identifier, name, profile image, granted permissions, encrypted tokens, and activity summaries: sport, date, visibility, distance, duration, elevation, speed, calories, and effort metrics when supplied by Strava. We retain up to one year of these summaries for historical comparisons. We do not store GPS, polylines, routes, or biometric streams.",
        "privacy_use_title": "How we use it", "privacy_use_text": "We use it to verify RUD@S membership, sync activities, and show your dashboard and internal rankings. We do not sell data or use it for advertising.",
        "privacy_control_title": "Control, access, and deletion", "privacy_control_text": "From Settings you can download a copy of the data Radar stores about you, include or remove access to Only You activities, and delete your account. When private access is removed, Radar deletes activities that are no longer accessible and recalculates totals. You can also revoke Radar Rudo in Strava.",
        "privacy_retention_title": "Retention and contact", "privacy_retention_text": "We retain data while you authorize the application. Contact the RUD@S administrator for privacy requests.",
        "delete_data": "Delete my Radar Rudo account and data", "delete_confirm": "Your Radar Rudo account, local data, and this app authorization will be deleted. Your Strava account and activities will not be deleted. You will need to connect Strava again to return.",
        "data_deleted": "Your Radar Rudo account and local data were deleted.", "powered_by": "Compatible with Strava", "positions": "Leaderboard", "ranked_by_time": "Ranked by active time", "athlete": "Athlete", "athlete_breakdown": "TEAM BREAKDOWN", "breakdown_privacy_note": "Totals by activity type. No schedules, routes, or individual workouts.", "activity_mix": "ACTIVITY MIX", "what_they_trained": "What they trained this period", "active_time": "Active time", "registered_members": "registered members", "active_members": "active participants", "team_sessions": "team sessions",
        "weekly_pulse": "PERIOD PULSE", "vs_last_week": "vs. previous period", "more_distance": "more total kilometers", "less_distance": "fewer total kilometers", "same_distance": "same total distance", "discipline_activity": "Activity by discipline", "biggest_distance_day": "Team's biggest-distance day", "period_stories": "Stories from this period", "your_summary": "YOUR SUMMARY", "total_period": "Period total", "swim": "Pool swim", "open_water": "Open water", "bike": "Bike", "run": "Run", "walk": "Walk / Hike", "strength": "Strength", "cardio": "Indoor cardio", "wellbeing": "Yoga / mobility", "pace_per_100m": "pace /100 m", "pace_per_km": "pace /km", "average_speed": "average speed", "team_community": "RUD@S community", "team_participation": "Participation", "team_activity": "Team activity", "team_time": "Time in motion", "team_distance": "Shared distance", "team_total": "this period", "complementary_training": "Strength and wellbeing", "your_longest_day": "Your longest-distance day", "your_busiest_day": "Your busiest day", "team_busiest_day": "RUD@S's busiest day", "team_discipline_days": "The team's biggest days", "participants": "participants", "sessions": "sessions", "gym": "Gym", "no_story_yet": "Your next activity starts this period's story.", "weekday_0": "Monday", "weekday_1": "Tuesday", "weekday_2": "Wednesday", "weekday_3": "Thursday", "weekday_4": "Friday", "weekday_5": "Saturday", "weekday_6": "Sunday",
    },
}

MESSAGES["es"].update({
    "account_menu": "Menú de cuenta", "your_radar": "TU RADAR", "greeting": "Qué onda,", "dashboard_kicker": "Elige una disciplina. Mira tu avance. Encuentra a quién alcanzar.",
    "period": "Periodo", "period_summary": "Resumen del periodo", "your_moving_time": "Tu tiempo en movimiento", "training_without_mixed_distance": "Todo tu entrenamiento, sin mezclar distancias", "previous_period_delta": "vs. periodo anterior", "period_consistency": "Constancia del periodo", "rudos_active": "RUD@S activos", "view_participants": "Ver participantes →",
    "each_sport_league": "CADA DEPORTE JUEGA SU PROPIA LIGA", "performance_challenge": "Tu rendimiento y el reto del equipo", "selected_period_data": "Datos del periodo seleccionado", "discipline": "Disciplina", "no_discipline_records": "Todavía no tienes registros de esta disciplina en el periodo.",
    "against_yourself": "CONTRA TI MISMO", "present_vs_past": "Presente vs. pasado", "time": "Tiempo", "current_period": "Periodo actual", "previous_period": "Periodo anterior", "rudos_league": "LA LIGA RUD@S", "setting_the_pace": "¿Quién está marcando el paso?", "next_session_opens_table": "La próxima sesión puede abrir esta tabla.", "view_all": "Ver todos", "view_less": "Ver menos",
    "whole_team": "TODO EL EQUIPO", "discipline_totals": "Totales por disciplina", "compared_previous": "Comparados con el periodo anterior", "team_today": "EL EQUIPO HOY", "team_happening": "Qué está pasando en RUD@S", "team_percent": "% del equipo", "best_day": "mejor día",
    "active_rudos": "RUD@S ACTIVOS", "period_participants": "Participantes del periodo", "discipline_participants": "Participantes de {discipline}", "no_period_activity": "Sin actividad en este periodo", "close": "Cerrar", "participant_details": "Ver quién participó →",
    "desc_swim": "Alberca y aguas abiertas", "desc_bike": "Ruta, montaña y gravel", "desc_run": "Carrera y trail", "desc_walk": "Caminata y senderismo", "desc_strength": "Pesas, crossfit, HIIT y funcional", "desc_cardio": "Elíptica, escaladora y remo indoor", "desc_wellbeing": "Yoga, Pilates y recuperación",
    "type_pool_swim": "Alberca", "type_road": "Ruta", "type_mtb": "MTB", "type_gravel": "Gravel", "type_trainer": "Rodillo", "type_run": "Carrera", "type_trail": "Trail", "type_walk": "Caminata", "type_hike": "Hiking", "type_weights": "Pesas", "type_crossfit": "CrossFit", "type_hiit": "HIIT", "type_functional": "Funcional", "type_elliptical": "Elíptica", "type_stair": "Escaladora", "type_row": "Remo", "type_indoor_row": "Remo indoor", "type_yoga": "Yoga", "type_pilates": "Pilates", "type_recovery": "Recuperación",
    "insight_new": "Nuevo punto de partida. Ya tienes una marca para superar.", "insight_empty": "Tu próxima sesión abre esta comparación.", "insight_up": "Vas {change}% arriba del periodo anterior.", "insight_down": "Estás {change}% abajo. Todavía hay tiempo para responder.", "insight_even": "Vas exactamente al ritmo del periodo anterior.",
    "strava_connected": "Strava conectado.", "purposeful_data": "Datos de rendimiento con propósito.", "reconnect_strava": "Volver a conectar Strava", "manage_strava": "Administrar mi conexión en Strava", "your_data": "Tus datos", "data_export_explanation": "Descarga una copia de los datos de perfil y resúmenes de actividad que Radar conserva sobre ti. La descarga no incluye tokens ni secretos.", "download_my_data": "Descargar mis datos", "support_contact": "Soporte y solicitudes de datos: solrak.m@gmail.com", "deletion_complete": "Tu cuenta y todos tus datos de Radar Rudo fueron eliminados correctamente.", "privacy_strava_monitoring": "Strava puede monitorear y recopilar datos de uso de la API para sus propios fines, de acuerdo con su Política de API.",
})

MESSAGES["en"].update({
    "account_menu": "Account menu", "your_radar": "YOUR RADAR", "greeting": "What's up,", "dashboard_kicker": "Choose a discipline. See your progress. Find someone to catch.",
    "period": "Period", "period_summary": "Period summary", "your_moving_time": "Your moving time", "training_without_mixed_distance": "All your training without mixing distances", "previous_period_delta": "vs. previous period", "period_consistency": "Consistency this period", "rudos_active": "Active RUD@S", "view_participants": "View participants →",
    "each_sport_league": "EVERY SPORT HAS ITS OWN LEAGUE", "performance_challenge": "Your performance and the team challenge", "selected_period_data": "Data for the selected period", "discipline": "Discipline", "no_discipline_records": "You do not have records for this discipline in the period yet.",
    "against_yourself": "AGAINST YOURSELF", "present_vs_past": "Present vs. past", "time": "Time", "current_period": "Current period", "previous_period": "Previous period", "rudos_league": "THE RUD@S LEAGUE", "setting_the_pace": "Who is setting the pace?", "next_session_opens_table": "The next session can open this table.", "view_all": "View all", "view_less": "View less",
    "whole_team": "THE WHOLE TEAM", "discipline_totals": "Totals by discipline", "compared_previous": "Compared with the previous period", "team_today": "THE TEAM TODAY", "team_happening": "What's happening in RUD@S", "team_percent": "% of the team", "best_day": "best day",
    "active_rudos": "ACTIVE RUD@S", "period_participants": "Participants this period", "discipline_participants": "{discipline} participants", "no_period_activity": "No activity this period", "close": "Close", "participant_details": "See who participated →",
    "desc_swim": "Pool and open-water swimming", "desc_bike": "Road, mountain and gravel", "desc_run": "Road and trail running", "desc_walk": "Walking and hiking", "desc_strength": "Weights, CrossFit, HIIT and functional", "desc_cardio": "Elliptical, stair stepper and indoor rowing", "desc_wellbeing": "Yoga, Pilates and recovery",
    "type_pool_swim": "Pool", "type_road": "Road", "type_mtb": "MTB", "type_gravel": "Gravel", "type_trainer": "Indoor trainer", "type_run": "Run", "type_trail": "Trail", "type_walk": "Walk", "type_hike": "Hike", "type_weights": "Weights", "type_crossfit": "CrossFit", "type_hiit": "HIIT", "type_functional": "Functional", "type_elliptical": "Elliptical", "type_stair": "Stair stepper", "type_row": "Rowing", "type_indoor_row": "Indoor rowing", "type_yoga": "Yoga", "type_pilates": "Pilates", "type_recovery": "Recovery",
    "insight_new": "A new starting point. You now have a mark to beat.", "insight_empty": "Your next session starts this comparison.", "insight_up": "You are {change}% above the previous period.", "insight_down": "You are {change}% below. There is still time to respond.", "insight_even": "You are exactly even with the previous period.",
    "strava_connected": "Strava connected.", "purposeful_data": "Performance data with purpose.", "reconnect_strava": "Reconnect Strava", "manage_strava": "Manage my connection on Strava", "your_data": "Your data", "data_export_explanation": "Download a copy of the profile data and activity summaries Radar stores about you. The download does not include tokens or secrets.", "download_my_data": "Download my data", "support_contact": "Support and data requests: solrak.m@gmail.com", "deletion_complete": "Your Radar Rudo account and all its data were deleted successfully.", "privacy_strava_monitoring": "Strava may monitor and collect API usage data for its own purposes under its API Policy.",
})


def translate(locale: str, key: str, **values: object) -> str:
    message = MESSAGES.get(locale, MESSAGES[DEFAULT_LOCALE]).get(key, MESSAGES[DEFAULT_LOCALE].get(key, key))
    return message.format(**values)


def preferred_locale(query_locale: str | None, session: Mapping[str, object]) -> str:
    if query_locale in SUPPORTED_LOCALES:
        return query_locale
    saved = session.get("locale")
    return saved if saved in SUPPORTED_LOCALES else DEFAULT_LOCALE
